version: '3.9'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ToDo:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A ToDo worker --loglevel=info
    volumes:
      - ./ToDo:/app
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=ToDo.settings

  celery-beat:
    build: .
    command: celery -A ToDo beat --loglevel=info
    volumes:
      - ./ToDo:/app
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=ToDo.settings

  bot:
    build: .
    command: python bot/bot.py
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
    env_file:
      - .env

volumes:
  postgres_data: